name: Sync Fixtures

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Call protected tRPC endpoint
        run: |
          curl -X POST https://admin-ln-foot.vercel.app/api/trpc/sync.syncData \
              -H "Content-Type: application/json" \
              -H "x-github-secret: ${{ secrets.SYNC_SECRET }}" \
              -d '{"input":null}'
